# Exported from Render on 2026-09-29T19:46:06Z
version: "1"
services:
- type: web
  name: shopnear-u96r
  runtime: docker
  repo: https://github.com/the-harshgupta/ShopNear
  plan: free
  envVars:
  - key: JWT_SECRET
    sync: false
  - key: SPRING_H2_CONSOLE_ENABLED
    sync: false
  region: singapore
  healthCheckPath: /api/stores
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
